'use strict';

exports.mentors = [{
  'username': 'seun',
  'role': 'mentor',
  'isApproved': true,
  'linkedIn': 'seun.linked.in',
  'photo': 'seun.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'seun@test.co',
  'lastName': 'Yamentor',
  'firstName': 'Seun'
}, {
  'username': 'Laide',
  'role': 'mentor',
  'isApproved': true,
  'linkedIn': 'Laide.linked.in',
  'photo': 'Laide.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'laide@test.co',
  'lastName': 'Yamentor',
  'firstName': 'Laide'
}, {
  'username': 'Jibola',
  'role': 'mentor',
  'isApproved': true,
  'linkedIn': 'Jibola.linked.in',
  'photo': 'Jibola.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'jibola@test.co',
  'lastName': 'Yamentor',
  'firstName': 'Jibola'
}, {
  'username': 'Dan',
  'role': 'mentor',
  'isApproved': true,
  'linkedIn': 'dan.linked.in',
  'photo': 'dan.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'dan@test.co',
  'lastName': 'Yamentor',
  'firstName': 'dan'
}, {
  'username': 'Tunde',
  'role': 'mentor',
  'isApproved': true,
  'linkedIn': 'tunde.linked.in',
  'photo': 'tunde.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'tunde@test.co',
  'lastName': 'Yamentor',
  'firstName': 'tunde'
}, {
  'username': 'Tony',
  'role': 'mentor',
  'isApproved': false,
  'linkedIn': 'tony.linked.in',
  'photo': 'tony.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'tony@test.co',
  'lastName': 'Yamentor',
  'firstName': 'tony'
}, {
  'username': 'Kenny',
  'role': 'mentor',
  'isApproved': true,
  'linkedIn': 'kenny.linked.in',
  'photo': 'kenny.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'kenny@test.co',
  'lastName': 'Yamentor',
  'firstName': 'kenny'
}];

exports.learners = [{
  'username': 'seun-l',
  'role': 'learner',
  'linkedIn': 'seun.linked.in',
  'photo': 'seun.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'seun@test.co',
  'lastName': 'Yamentor',
  'firstName': 'Seun'
}, {
  'username': 'Laide-l',
  'role': 'learner',
  'linkedIn': 'Laide.linked.in',
  'photo': 'Laide.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'laide@test.co',
  'lastName': 'Yamentor',
  'firstName': 'Laide'
}, {
  'username': 'Jibola-l',
  'role': 'learner',
  'linkedIn': 'Jibola.linked.in',
  'photo': 'Jibola.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'jibola@test.co',
  'lastName': 'Yamentor',
  'firstName': 'Jibola'
}, {
  'username': 'Dan-l',
  'role': 'learner',
  'linkedIn': 'dan.linked.in',
  'photo': 'dan.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'dan@test.co',
  'lastName': 'Yamentor',
  'firstName': 'dan'
}, {
  'username': 'Tunde-l',
  'role': 'learner',
  'linkedIn': 'tunde.linked.in',
  'photo': 'tunde.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'tunde@test.co',
  'lastName': 'Yamentor',
  'firstName': 'tunde'
}, {
  'username': 'Tony-l',
  'role': 'learner',
  'linkedIn': 'tony.linked.in',
  'photo': 'tony.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'tony@test.co',
  'lastName': 'Yamentor',
  'firstName': 'tony'
}, {
  'username': 'Kenny-l',
  'role': 'learner',
  'linkedIn': 'kenny.linked.in',
  'photo': 'kenny.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'kenny@test.co',
  'lastName': 'Yamentor',
  'firstName': 'kenny'
}, {
  'username': 'Chitech-l',
  'role': 'learner',
  'linkedIn': 'chitech.linked.in',
  'photo': 'chitech.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'chitech@test.co',
  'lastName': 'Yamentor',
  'firstName': 'chitech'
}, {
  'username': 'Ashikodi-l',
  'role': 'learner',
  'linkedIn': 'ashi.linked.in',
  'photo': 'ashi.jpg',
  'bio': 'master bot',
  'address': 'Lagos',
  'provider': 'local',
  'password': '11111111',
  'email': 'ashi@test.co',
  'lastName': 'Yamentor',
  'firstName': 'ashi'
}];
